# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 22:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20170628_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('kind',
                 models.CharField(choices=[('E', 'Email'), ('P', 'Phone')],
                                  max_length=1)),
                ('value', models.CharField(max_length=255)),
                ('speaker',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='core.Speaker')),
            ],
        ),
    ]
